# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  
env:
  TEAMS_WEBHOOK_URL: 'https://ofpptcasa.webhook.office.com/webhookb2/9357c2cf-f188-462e-86e0-02a09ddcb154@dae54ad7-43df-47b7-ae86-4ac13ae567af/IncomingWebhook/8fcc3cef1db24588a91dc4101daca6ff/d23e1664-7319-4a34-bd32-512fc6772eb9'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
